### PR TITLE
fix #265

### LINKED ISSUE #265: unhashable type: 'ColouredText'
**Describe the bug**
The new `ColouredText` class (which is super nice btw) that a lot of the widgets can now use is sometimes directly passed to `wcwidth` in the `Frame` class which casues the exception `TypeError: unhashable type: 'ColouredText'`.

This seems to only affect certain widgets like the `ListBox`. 

https://github.com/peterbrittain/asciimatics/blob/476159c95c5b6e34a782ea97503785ad95683805/asciimatics/widgets.py#L2776

The solution seems to be something like this line where `str()` is called on the `ColouredText` object.

https://github.com/peterbrittain/asciimatics/blob/476159c95c5b6e34a782ea97503785ad95683805/asciimatics/widgets.py#L2919

But I'm not sure if this fixes it in all cases or if there are any other issues doing it this way.

**To Reproduce**

```python
from asciimatics.widgets import Frame, ListBox, Layout, Divider, Button, Widget
from asciimatics.scene import Scene
from asciimatics.screen import Screen
from asciimatics.exceptions import ResizeScreenError, StopApplication
from asciimatics.parsers import AsciimaticsParser
import sys


class ListTestView(Frame):
    def __init__(self, screen):
        super(ListTestView, self).__init__(screen,
                                           screen.height * 2 // 3,
                                           screen.width * 2 // 3,
                                           hover_focus=True,
                                           can_scroll=False,
                                           title="Test List")

        self._running_test_list_view = ListBox(
            Widget.FILL_COLUMN,
            [(r'${15}● Test 1', 1)], # <- inserted color code
            name="running tests",
            parser=AsciimaticsParser(), # <- color code parser
            add_scroll_bar=True)
        
        # 1st layout
        layout = Layout([100], fill_frame=True)
        self.add_layout(layout)
        layout.add_widget(self._running_test_list_view, 0)
        layout.add_widget(Divider(), 0)

        # 2nd layout
        layout2 = Layout([1, 1])
        self.add_layout(layout2)
        layout2.add_widget(Button("Quit", self._quit), 1)
        self.fix()

    @staticmethod
    def _quit():
        raise StopApplication("User pressed quit")


def menu(screen, scene):
    scenes = [
        Scene([ListTestView(screen)], -1, name="Main"),
    ]
    screen.play(scenes, stop_on_resize=True, start_scene=scene, allow_int=True)


last_scene = None
while True:
    try:
        Screen.wrapper(menu, arguments=[last_scene])
        sys.exit(0)
    except ResizeScreenError as e:
        last_scene = e.scene
```

**Expected behavior**
No exception.

**System details (please complete the following information):**
 - OS and version: Ubuntu 20.04
 - Asciimatics version: master branch (commit 476159c)

**Additional context**
<details>
  <summary>Full Traceback</summary>

```
$ python3.8 broken.py 
Traceback (most recent call last):
  File "broken.py", line 53, in <module>
    Screen.wrapper(menu, arguments=[last_scene])
  File ".venv/ces-soc-cc-user_client/lib/python3.8/site-packages/asciimatics/screen.py", line 1379, in wrapper
    return func(screen, *arguments)
  File "broken.py", line 47, in menu
    screen.play(scenes, stop_on_resize=True, start_scene=scene, allow_int=True)
  File ".venv/ces-soc-cc-user_client/lib/python3.8/site-packages/asciimatics/screen.py", line 1548, in play
    self.draw_next_frame(repeat=repeat)
  File ".venv/ces-soc-cc-user_client/lib/python3.8/site-packages/asciimatics/screen.py", line 1651, in draw_next_frame
    effect.update(self._frame)
  File ".venv/ces-soc-cc-user_client/lib/python3.8/site-packages/asciimatics/effects.py", line 71, in update
    self._update(frame_no)
  File ".venv/ces-soc-cc-user_client/lib/python3.8/site-packages/asciimatics/widgets.py", line 462, in _update
    layout.update(frame_no)
  File ".venv/ces-soc-cc-user_client/lib/python3.8/site-packages/asciimatics/widgets.py", line 1255, in update
    widget.update(frame_no)
  File "/.venv/ces-soc-cc-user_client/lib/python3.8/site-packages/asciimatics/widgets.py", line 2776, in update
    paint_text += " " * (width - self.string_len(paint_text))
  File ".venv/ces-soc-cc-user_client/lib/python3.8/site-packages/wcwidth/wcwidth.py", line 245, in wcswidth
    wcw = wcwidth(char, unicode_version)
TypeError: unhashable type: 'ColouredText'
```

</details>

### PR DESCRIPTION
**Pull request by komodo472**
Issues fixed by this PR
-----------------------
#265

### CODE REVIEW

**Comment by komodo472** [comment]
I added an additional fix for setting the options property on the ListBox. It now uses the  `_BaseListBox` `_parse_option()` method to correctly check for a color parser.

**Comment by peterbrittain** [comment]
Looks sensible to me.  Any chance that you can update the test in test_widgets to hit this code?

**Comment by komodo472** [comment]
Yes, I'll give it a go.

**Comment by peterbrittain** [comment]
Much appreciated!

**Comment by komodo472** [comment]
So I've been looking over the tests and I found that nosetest is running with `unicode_aware` as False, causing all of the widgets to use the built-in `len()` function and not `wcswidth` even when unicode text is being passed to the methods. This is why some of the tests were passing when the fixes I implemented above should've been failing the tests. I think the offending line is the following:
https://github.com/peterbrittain/asciimatics/blob/476159c95c5b6e34a782ea97503785ad95683805/asciimatics/widgets.py#L1487
As I thought more about the tests after discovering this, I'm unsure what might be the best fix. It seems that unicode should not be allowed in the widgets if the current terminal is not unicode aware, but that might not be easy/doable. Something else that could be done is to change the `register_frame()` method to always use `wcswidth` if there is a `_parser`. Lastly, I could write a test that forces nosetest to be unicode aware but that seems to me to be the least desirable option.

Any input on the best way to fix this would greatly appreciated.

**Comment by peterbrittain** [comment]
Not quite all the tests run in non-unicode environments.  S9me tests set unicode_aware=True.  That's totally fine for the tests that need it, so if that's all you need, feel free to set it up accordingly.

**Comment by komodo472** [comment]
@peterbrittain Done

**Pull request merged**
