### PR TITLE
Added new typewriter effect

### LINKED ISSUE #263: Left to right rendering effect
**Is your feature request related to a problem? Please describe.**
I would like for an effect to render text (or ASCII characters) from left to right, like it's being typed out.

**Describe the solution you'd like**
Similar to the mirage effect (where text can be rendered one character at a time, only randomly), it would be cool to have text rendered one letter at a time from left to right, so it appears to be typed in real-time.

### PR DESCRIPTION
**Pull request by mjip**
Issues fixed by this PR
-----------------------
Closes #263 

What does this implement/fix?
-----------------------------

Any other comments?
-------------------

### CODE REVIEW

**Comment by peterbrittain** [comment]
Thanks.  I just tried running it live and it didn't do what I expected...  I think there are a couple of bugs and some possible improvements we could make here.  I'll try to add some comments to the code to explain.

**Comment by peterbrittain** [comment]
Hope that all makes sense...  Do you think you can make those changes?

**Comment by mjip** [comment]
For sure. Document the issues you see here, and I'll try writing up some more extensive examples to look at on my end (I was using a SpeechBubble static renderer)

**Comment by peterbrittain** [comment]
Thanks.  Detailed comments are in the review.  Main bug I saw was that the first column of text was offset from the rest on my test.  Hope that helps!

**Comment by mjip** [comment]
Thanks for taking the time to review! Only, I can't seem to find it- have you published it yet? This could also perhaps be one of the Github redesign's quirks

**Comment by peterbrittain** [comment]
@mjip Any luck with those changes?

**Comment by mjip** [comment]
I haven't had the time to take a look lately, but I'm hoping to revisit it next week. Thanks for the review though!

**Pull request closed without merging**
