### PR TITLE
Move to Python 3 only

### LINKED ISSUE #347: Drop python 2 support
Please consider to drop mock from requirements.

### PR DESCRIPTION
**Pull request by s-t-e-v-e-n-k**
With setup.py declaring Python 3.8 and above is supported, use pyupgrade to reformat the code for that version, along with removing use of mock and future modules.

Fixes #347

### CODE REVIEW

**Review by peterbrittain — CHANGES_REQUESTED** [review]
Nice!  Thanks.  The code changes look great!  Just spotted a couple of isxues in the docs.  The troubleshooting is called out in the review.  Could you also please update CHANGES.rst to say that python 2 support was removed?

Finally, I see that the travis build failed because of 2 reasons:

- The pypy run is using Python 2 - worth trying pypy3 instead to see if we can pick up a modern version.
- The Windows 3.8 version is failing because of PyFiglet is using an API that doesn't exist until 3.9 - let's move to 3.9 while I try to get a patch in their code.

**Comment by s-t-e-v-e-n-k** [comment]
Updated to 3.9 for Windows and pypy3 :crossed_fingers:

**Comment by s-t-e-v-e-n-k** [comment]
Well, I fixed one, I wasn't expecting 3.9 to install 3.9.0 :-( Not sure why pip isn't upgrading

**Comment by peterbrittain** [comment]
Ok...  Nearly there!  I think the Windows build issue is because you needed to change the PATH to match the installed version.  

Pyfiglet code should now be fixed so that older versions of Python will not pick up the new 1.0.0 release.  Let's try moving windows back to 3.8.9 and see if it all builds cleanly now.

I'll happily merge once that's passing.

**Pull request merged**
