### PR TITLE
Added on_focus & on_blur callbacks on widget

### PR DESCRIPTION
**Pull request by dylanjsa**
Allows a user to set widget._on_focus and widget._on_blur for handling those events.

### CODE REVIEW

**Comment by peterbrittain** [comment]
Exactly the implemenration I had in mind.  Thanks.  Any chance you could add a test that proves the callbacks work?

**Comment by dylanjsa** [comment]
Cool! Yep for sure, got some reading to do though.

**Comment by peterbrittain** [comment]
Thanks.  If you're looking for a quick start on mocking out a Frame with a couple of widgets in it, `test_password` is a good template.  You can then use the `process_keys` or `process_mouse` methods to inject input to make the focus move.

**Comment by dylanjsa** [comment]
Thanks again for the help, I've created the test case (apologies if the implementation isn't what you expected, I couldn't think of a different way to do it).

It seems to have a conflict. I bet this is because I was working on the v1.8 branch, I had to do this because the master branch wasn't working. (my _on_change callbacks in master were never running).

**Comment by peterbrittain** [comment]
OK - I've had a go at tidying this up for you.  I've had to create a new pull request in the process.  Have a look at https://github.com/peterbrittain/asciimatics/pull/99 instead of this PR now.

**Comment by dylanjsa** [comment]
thanks peter

**Pull request closed without merging**
