### PR TITLE
[WIP] Add mypy stubs (Fixes #240)

### LINKED ISSUE #240: Provide library stubs (type hinting) for compatibility with Mypy (e.g.: typeshed)
At the moment the lack of type hinting requires turning off mypy checks. It would be helpful to offer library stubs.

### PR DESCRIPTION
**Pull request by JPTIZ**
# Thanks for taking the time to contibute to this project.  You are a star!

Checks
------
_Before you go any further, please make sure that you have read the [contributing guidelines](https://asciimatics.readthedocs.io/en/latest/contributing.html), run the test suite and that your clone of this repository was taken after 18 October 2018.  (I had to fix up the git history and so clones before that date will have all sorts of merge issues)._ 

_Now please delete this pre-amble section and fill in the rest of the template..._

Issues fixed by this PR
-----------------------

- #240 

What does this implement/fix?
-----------------------------

This PR:
- Adds stubgen-generated stubs for the following libraries:
  - `future`
- Adds missing typehints that mypy complains about

Any other comments?
-------------------

This is a WIP

### CODE REVIEW

**Comment by peterbrittain** [comment]
I don't think we should be adding future stubs to asciimatics...  Have you offered them to the future package maintainer instead?

**Comment by peterbrittain** [comment]
Looks like they might be amenable....  https://github.com/PythonCharmers/python-future/issues/490

**Comment by JPTIZ** [comment]
> I don't think we should be adding future stubs to asciimatics... Have you offered them to the future package maintainer instead?

Hm, didn't think about that. That could be a solution, yes. I also agree that having the stubs in our repo wouldn't be very nice. 

> Looks like they might be amenable.... [PythonCharmers/python-future#490](https://github.com/PythonCharmers/python-future/issues/490)

Indeed haha. Time to solve a 1 and a half year old issue. Ok, so I'll send them a PR and, in the meanwhile, solve other things with this one.

Would you recommend me to send PIL a similar PR? Since Mypy complained about stubs for it as well. They also have an open issue for that: https://github.com/python-pillow/Pillow/issues/2625.

**Comment by peterbrittain** [comment]
Yeah - it looks like they also ground to a halt.  Might be worth pointing out that type stubs can now be used in the package according to https://www.python.org/dev/peps/pep-0561/

**Pull request closed without merging**
