### PR TITLE
RegEx filtering option for FileBrowser

### PR DESCRIPTION
**Pull request by kirtansakariya**
Issues fixed by this PR
-----------------------
#186 

What does this implement/fix?
-----------------------------
Added a new RegEx option to the `FileBrowser` to allow filtering of files

Any other comments?
-------------------
If you need me to change anything, please let me know.

### CODE REVIEW

**Comment by kirtansakariya** [comment]
I'll push up a change to resolve the Codacy Issue

**Comment by peterbrittain** [comment]
As for the coveralls comment...  Just create another test that looks like `test_file_browser`, but pass in a filter that removes some of the returned results.

**Comment by kirtansakariya** [comment]
Hmm. I'm looking into why it's failing. It works on my local copy when I run `nosetests`.

**Comment by kirtansakariya** [comment]
Oh I see, the issue is with the use of the `re.fullmatch` function. It isn't supposed before python 3.4. I'm working on a fix to use `re.match` instead of `re.fullmatch`

**Comment by peterbrittain** [comment]
Looked good to me.  I've just fixed some docs issues and added you to the credits.  

Thanks very much for your contribution!

**Comment by kirtansakariya** [comment]
Thanks for letting me contribute! I was wondering, do you have an estimated date for the next release?

**Comment by peterbrittain** [comment]
You're welcome!  

I tend to wait until there is a good set of new features before I package up a new release these days.  I wouldn't expect that to be for several months yet, but have no specific time-frame in mind.  In the meantime, you can always use github code directly.  See https://stackoverflow.com/questions/8247605/configuring-so-that-pip-install-can-work-from-github

**Comment by kirtansakariya** [comment]
Alright, thanks.

**Pull request merged**
