### PR TITLE
Effect class is imported wrong, Fails to create cache files inside a new directory.

### PR DESCRIPTION
**Pull request by billyeatcookies**
What issues does this fix?
-----------------------------
- [x] Effect class is imported wrong in samples/maps.py (#306)
- [x] Error while creating/reading created cache files (samples) (#307)

What does this implement/fix?
-----------------------------
- [x] Fixed import of Effect class
- [x] Fixed errors while creating cache files.

### CODE REVIEW

**Comment by peterbrittain** [comment]
Import change is good.  Not so keen onnthe cache change...  It's meant to use a separate directory.  A better fix would be to make it ensure that directory exists on start up.  Are you happy to make that change?

**Comment by billyeatcookies** [comment]
python fails to create a file inside another folder, that was the main problem I was facing.

**Comment by billyeatcookies** [comment]
first creating a directory, and then saving the files worked! i shall implement it.
image

**Comment by peterbrittain** [comment]
Excellent!  That is exactly the sort of fix that I was talking about.

**Comment by peterbrittain** [comment]
Looking better.  A slightly simpler solution would be just to call `mkdir` in `Map.__init__`.  This will always run before any of those commands and so ensure that the directory exists.  If a user actually deletes the directory while running, you'll hit an exception and that would be justified IMHO.

**Comment by billyeatcookies** [comment]
will it be good, if custom exceptions will be raised if the directory doesn't exist
> ```py
> if not os.path.isdir('mapscache'):
>        # instead of just returning none, raise a CacheFilesNotFound exception
> ```

**Pull request merged**
