### PR TITLE
Expose a focussed widget property.

### PR DESCRIPTION
**Pull request by lwm**
Well, following my proclamation in https://github.com/peterbrittain/asciimatics/issues/154#issuecomment-397868927, I decided I better do something :)

Here's a first stab at contributing here.

Closes https://github.com/peterbrittain/asciimatics/issues/124.

### CODE REVIEW

**Comment by peterbrittain** [comment]
Thanks for this.  Help is always appreciated!  Just two comments:

1. Feel free to add yourself to the credits roll if you like.
2. I think this should check whether the Frame has the focus and any Layouts and return `None` if either is true.

**Comment by lwm** [comment]
Thanks for reviewing @peterbrittain. Gave it another stab.

**Comment by peterbrittain** [comment]
Looking good.  There are just a couple of tweaks needed, one of which is coz I was ambiguous in my previous comments.  Will fix and merge myself to make amends.

**Comment by lwm** [comment]
> one of which is coz I was ambiguous in my previous comments.

hehe, I did have to squint my eyes a bit ... ;)

> Will fix and merge myself to make amends.

:+1: :+1: :+1:

**Comment by peterbrittain** [comment]
If you think I've said something stupid, feel free to double check in the future.  We're all only human.

I've fixed it up and merged,

**Pull request merged**
