### PR TITLE
Added options setter for DropdownList

### PR DESCRIPTION
**Pull request by egakupi**
Issues fixed by this PR
-----------------------
Missing the options setter for DropdownList widget

### CODE REVIEW

**Comment by peterbrittain** [comment]
Thanks for submitting this change...  Just a couple of tweaks would be great if you're up for it...

1) The other widgets that support changing options try to reset the old value (by just setting the value property to the internal _value object.  Could you do the same here?
2) Could you pleaae add a test for this new function?  See  test_multi_column_list_box for the test code the checks optionx for that widget.

**Comment by egakupi** [comment]
Sorry, I have some issues with nosetests and renderers but I checked set and read manually. Seems good.

**Comment by peterbrittain** [comment]
Renderers depend on algorithmd in Pillow, wh8ch is why the dev environment pins the version.  Looks good to me!  If you'd also like to add your name to credits.py in a separate PR, please do!

**Comment by peterbrittain** [comment]
Many thanks!

**Pull request merged**
